In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [47]:
dataset = pd.read_csv('Employee_Salary_Dataset.csv')
x= dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [48]:
dataset

ID  Experience_Years  Age  Gender    Salary
0    1                 5   28  Female    250000
1    2                 1   21    Male     50000
2    3                 3   23  Female    170000
3    4                 2   22    Male     25000
4    5                 1   17    Male     10000
5    6                25   62    Male   5001000
6    7                19   54  Female    800000
7    8                 2   21  Female      9000
8    9                10   36  Female     61500
9   10                15   54  Female    650000
10  11                 4   26  Female    250000
11  12                 6   29    Male   1400000
12  13                14   39    Male   6000050
13  14                11   40    Male    220100
14  15                 2   23    Male      7500
15  16                 4   27  Female     87000
16  17                10   34  Female    930000
17  18                15   54  Female   7900000
18  19                 2   21    Male     15000
19  20                10   36    Male    330000
20  21                15   54    Male   6570000
21  22                 4   26    Male     25000
22  23                 5   29    Male   6845000
23  24                 1   21  Female      6000
24  25                 4   23  Female      8900
25  26                 3   22  Female     20000
26  27                 1   18    Male      3000
27  28                27   62  Female  10000000
28  29                19   54  Female   5000000
29  30                 2   21  Female      6100
30  31                10   34    Male     80000
31  32                15   54    Male    900000
32  33                20   55  Female   1540000
33  34                19   53  Female   9300000
34  35                16   49    Male   7600000

In [35]:
print(x)

[[1 5 28 'Female']
 [2 1 21 'Male']
 [3 3 23 'Female']
 [4 2 22 'Male']
 [5 1 17 'Male']
 [6 25 62 'Male']
 [7 19 54 'Female']
 [8 2 21 'Female']
 [9 10 36 'Female']
 [10 15 54 'Female']
 [11 4 26 'Female']
 [12 6 29 'Male']
 [13 14 39 'Male']
 [14 11 40 'Male']
 [15 2 23 'Male']
 [16 4 27 'Female']
 [17 10 34 'Female']
 [18 15 54 'Female']
 [19 2 21 'Male']
 [20 10 36 'Male']
 [21 15 54 'Male']
 [22 4 26 'Male']
 [23 5 29 'Male']
 [24 1 21 'Female']
 [25 4 23 'Female']
 [26 3 22 'Female']
 [27 1 18 'Male']
 [28 27 62 'Female']
 [29 19 54 'Female']
 [30 2 21 'Female']
 [31 10 34 'Male']
 [32 15 54 'Male']
 [33 20 55 'Female']
 [34 19 53 'Female']
 [35 16 49 'Male']]


In [49]:
print(y)

[  250000    50000   170000    25000    10000  5001000   800000     9000
    61500   650000   250000  1400000  6000050   220100     7500    87000
   930000  7900000    15000   330000  6570000    25000  6845000     6000
     8900    20000     3000 10000000  5000000     6100    80000   900000
  1540000  9300000  7600000]


In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [39]:
print(x)

[[1.0 0.0 1 5 28]
 [0.0 1.0 2 1 21]
 [1.0 0.0 3 3 23]
 [0.0 1.0 4 2 22]
 [0.0 1.0 5 1 17]
 [0.0 1.0 6 25 62]
 [1.0 0.0 7 19 54]
 [1.0 0.0 8 2 21]
 [1.0 0.0 9 10 36]
 [1.0 0.0 10 15 54]
 [1.0 0.0 11 4 26]
 [0.0 1.0 12 6 29]
 [0.0 1.0 13 14 39]
 [0.0 1.0 14 11 40]
 [0.0 1.0 15 2 23]
 [1.0 0.0 16 4 27]
 [1.0 0.0 17 10 34]
 [1.0 0.0 18 15 54]
 [0.0 1.0 19 2 21]
 [0.0 1.0 20 10 36]
 [0.0 1.0 21 15 54]
 [0.0 1.0 22 4 26]
 [0.0 1.0 23 5 29]
 [1.0 0.0 24 1 21]
 [1.0 0.0 25 4 23]
 [1.0 0.0 26 3 22]
 [0.0 1.0 27 1 18]
 [1.0 0.0 28 27 62]
 [1.0 0.0 29 19 54]
 [1.0 0.0 30 2 21]
 [0.0 1.0 31 10 34]
 [0.0 1.0 32 15 54]
 [1.0 0.0 33 20 55]
 [1.0 0.0 34 19 53]
 [0.0 1.0 35 16 49]]


In [40]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [41]:
x_train

array([[0.0, 1.0, 35, 16, 49],
       [1.0, 0.0, 33, 20, 55],
       [0.0, 1.0, 27, 1, 18],
       [0.0, 1.0, 31, 10, 34],
       [1.0, 0.0, 9, 10, 36],
       [0.0, 1.0, 14, 11, 40],
       [0.0, 1.0, 6, 25, 62],
       [1.0, 0.0, 18, 15, 54],
       [0.0, 1.0, 15, 2, 23],
       [0.0, 1.0, 32, 15, 54],
       [1.0, 0.0, 25, 4, 23],
       [0.0, 1.0, 2, 1, 21],
       [0.0, 1.0, 13, 14, 39],
       [1.0, 0.0, 7, 19, 54],
       [1.0, 0.0, 24, 1, 21],
       [0.0, 1.0, 5, 1, 17],
       [0.0, 1.0, 19, 2, 21],
       [0.0, 1.0, 22, 4, 26],
       [0.0, 1.0, 20, 10, 36],
       [1.0, 0.0, 10, 15, 54],
       [1.0, 0.0, 8, 2, 21],
       [1.0, 0.0, 34, 19, 53],
       [0.0, 1.0, 4, 2, 22],
       [1.0, 0.0, 1, 5, 28]], dtype=object)

In [42]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [43]:
y_pred=regressor.predict(x_test)


In [44]:
y_pred

array([ 585950.84847417, 2922228.78114561, 1976441.19896541,
       4546092.63225056,  875952.76466121,  335053.87660599,
        145888.22988886, -413597.01150139,  685292.07194691,
       6680257.94322285,  675780.29945358])

In [50]:
y_test

array([    6100,  6570000,   930000,  5000000,  6845000,    87000,
         250000,   170000,  1400000, 10000000,    20000])